### ISSUE TITLE
the layout of output file of treeBreaker

### ISSUE THREAD

**Issue by lindechun** [ansariazim/treeBreaker#2]
i gave put the correct parameter “inputfile_tree inputfile_phenotype outputfile”，and No error was reported during operation, but the last line of output file of treeBreaker isn't contains the newick string of the tree

**Comment by ansariazim** [comment]
Hi there,
Could you leave your sample tree file and the pheno file on here. I'll have a look to see what is wrong.
Best.
Azim

**Comment by lindechun** [comment]
Yeah, I have tested the test data in the 'testData' directory and the result is correct.

I upload my tree file and pheno file on here, and the command is that "
    treeBreaker 6829_ML.tree MDR 6829_treeBreaker.txt
    treeBreaker.R 6829_treeBreaker.txt 6829_treeBreaker"

Thank you for helping me check for mistakes.

[treeBreaker_file.zip](https://github.com/ansariazim/treeBreaker/files/2139546/treeBreaker_file.zip)

**Comment by ansariazim** [comment]
Hi there, I ran treeBreaker on your files and it worked fine. Not sure what the problem is. Maybe you need to recompile it. If you still have problems, I might be able to send you binaries compiled on osx.

Just for consistancy, some of your internal nodes have names (numeric names like 0.269) and some don't. It might make more sense to be consistant, ie either name all internal nodes or don't name any of them. The other thing is that numeric names like 0.269 might not be unique, I don't think that causes any problem for treeBreaker, but for other programs it might. 

I also suggest that you run treeBreaker for at least 10 million iterations (maybe even 100 million) as you have a very big tree and the MCMC needs time to explore all the branches of the tree.

**Comment by lindechun** [comment]
Hi, Azim
Firstly, I install treeBreaker on top of gsl that installed locally. and the test result of 'test data ' is not problems.
Could you give me the binaries compiled on **linux** ?
Thanks for the suggestion about -x, -y, -z (iterations) setting of run treeBreaker.

**Comment by ansariazim** [comment]
I don't have linux. But if you can run treeBreaker on testData then I would say it works fine. For the data that you sent me can you run it as follows
treeBreaker -x 1000 -y 1000 -z 100 6829_ML.tree MDR output

and send me the output file.

**Comment by lindechun** [comment]
Hi, I again ran treeBreaker on these files and it worked fine after re-install treeBreaker.
In addition, because the filename of output of treeBreaker is freewill, so I added the command-line arguments of treeBreaker.R
[treeBreaker.R.zip](https://github.com/ansariazim/treeBreaker/files/2144175/treeBreaker.R.zip)
